---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен выводить названия товара в каталоге и на странице товара.
  - Сайт должен отображать рейтинг товара.
  - Пользователь должен иметь возможность просматривать цены со скидкой и без скидки.
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления в корзину.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность оформить заказ
  - Пользователь должен иметь возможность оплатить заказ
  - Пользователь должен иметь возможность вернуться к своему заказу в любое время
  - Пользователь должен иметь доступ только к своим заказам
  - Пользователь не может редактировать описание товара.
  - Пользователь должен иметь возможность изменять количество товаров в корзине или удалять товары из корзины.
  - Пользователь должен видеть итоговую стоимость заказа в корзине.
